config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes do
    resources :ingredients
  end
  resources :recipes do
    resources :steps
  end
  resources :categories do
    resources :recipes, only: :index
  end
  root 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :recipes
  validates :name, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  validates :name, :qty, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
  has_many :steps
  has_and_belongs_to_many :categories

  
  scope :three_most_recent, -> {order(created_at: :desc).limit(3)}
  
  def self.search(search)
    Recipe.left_joins(:categories).where("recipes.title ILIKE ? or recipes.description ILIKE ? or categories.name ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%").distinct
  end

end

# This could work for self.search but it's longer
# def self.search(search)
#   (Recipe.where("title ILIKE ? or description ILIKE ?", "%#{search}%", "%#{search}%") +   get_recipes_from_categories(search)).uniq
# end
# def self.get_recipes_from_categories(search)
#   #searched categories
#   searched_categories = Category.where("name ILIKE ?", "%#{search}%")
#   #recipes
#   searched_categories.map{|category| category.recipes}.flatten
# end

###!!! This doesn't work for self.search because .includes loads only and doesn't query !!!###
# Recipe.includes(:categories).where("recipes.title ILIKE ? or recipes.description ILIKE ? or categories.name ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.includes(:recipes)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "Category is successfully created!"
    else
      render "new"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path, notice: "Category is successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to categories_path, notice: "Category is successfully deleted!"
    end
  end
  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.new(recipe_id: params[:recipe_id])
  end
  
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to recipe_path(@recipe), notice: 'Ingredient was successfully added.'
    else
      render 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(params[:id])
    #@ingredient = @recipe.ingredients.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to recipe_path(@recipe), notice: "Ingredient was successfully updated."
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.destroy
      redirect_to recipe_path(@recipe), notice: 'Recipe was successfully deleted.'
    end
  end

  private 
    def ingredient_params
      params.require(:ingredient).permit(:name, :qty, :uom, :recipe_id)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only:[:show, :edit, :update, :destroy]

  def index
    
    @three_most_recent = Recipe.three_most_recent
    if (params[:search])
      @recipes = Recipe.search(params[:search])
    elsif(params[:category_id])
      @category = Category.find(params[:category_id])
      @recipes = @category.recipes
    else
      if (params[:sort] == "newest")
        @recipes = Recipe.all.order(created_at: "desc")
        @categories = Category.includes(:recipes)
      else
        @recipes = Recipe.order(:title)
      end
    end
  end

  def show
    @steps = @recipe.steps
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe), notice: 'Recipe was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    if @recipe.destroy
      redirect_to recipes_path
    else
      render 'show'
    end
  end


  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:title, :description, category_ids:[])
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.new(recipe_id: params[:recipe_id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.new(step_params)
    if @step.save
      redirect_to recipe_path(@recipe), notice: "Step is successfully added!"
    else
      render 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.find(params[:id])
    if @step.update(step_params)
      redirect_to recipe_path(@recipe), notice: "Step is successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @step = @recipe.steps.find(params[:id])
    if @step.destroy
      redirect_to recipe_path(@recipe), notice: "Step is successfully deleted!"
    end
  end
  
  private
    def step_params
      params.require(:step).permit(:index, :description, :recipe_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <% if @category.errors.messages[:name].any? %>
      <span class='error'><%= @category.errors.messages[:name][0]%></span>
    <% end%>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
  <h2>Edit <%= @category.name %> </h2>

  <%= render "form" %>

  <button type="button" class="btn btn-outline-secondary"><%= link_to "Back to Categories", categories_path %></button>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <div  class="col">
      <h2>Categories</h2>
    </div>  
    <div  class="col mt-3">
      <button type="button" class="btn btn-outline-secondary"><%= link_to "Create Category", new_category_path %></button> 
    </div>  
  </div>

    <ul>
      <% @categories.each do |category| %>
        <li><p><%= link_to category.name, category_recipes_path(category) %> <%= link_to "[Edit]", edit_category_path(category) %> <%= link_to "[x]", category_path(category), method: :delete, data: {confirm: "Are you sure?"} %></p></li>
      <% end %>
    </ul>

    <button type="button" class="btn btn-outline-secondary"><%= link_to "Back to Recipes", recipes_path %></button>
</div>

app/views/categories/new.html.erb
  <h2>Create new category</h2>

  <%= render "form" %>

  <button type="button" class="btn btn-outline-secondary"><%= link_to "Back to Categories", categories_path %></button>
  <button type="button" class="btn btn-outline-secondary"><%= link_to "Back to Recipes", recipes_path %></button>

app/views/ingredients/_form.html.erb
<%= form_for [@recipe, @ingredient] do |f| %>
   <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% @ingredient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe_id %>
    <%= f.select :recipe_id, Recipe.order(:title).pluck(:title, :id), include_blank: true%>
  </div>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :qty %>
    <%= f.text_field :qty %>
  </div>

  <div class="field">
    <%= f.label :uom %>
     <%= f.select :uom, [["", ""],["cup", "cup"], ["tea spoon", "tea spoon"], ["table spoon", "table spoon"]] %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', :class => "btn btn-outline-secondary submit-btn"%>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<div class="container">
  <h2>Edit Ingredients</h2>
  <%= render "form" %>
  <div>
      <button type="button" class="btn btn-outline-secondary"><%= link_to 'Back', recipe_path(@recipe) %></button>
  </div>
</div>

app/views/ingredients/new.html.erb
<div class="container">
  <h2>Add Ingredients</h2>
  <%= render "form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyReciperails2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@800&display=swap" rel="stylesheet">
  </head>

  <body>
        <% flash.each do |type, msg| %>
          <div class="alert alert-info">
            <%= msg %>
          </div>
        <% end %>
        <div class="container">
          <%= yield %>
        </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: @recipe, local: true) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label "Category" %><br />
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
    <% end %>
</div>

  <div class="actions">
    <%= f.submit :class => "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="container">
  <h1>Edit <%= @recipe.title %></h1>
  <%= render 'form' %>
  <div>
    <p><%= link_to 'Back', recipe_path(@recipe) %></p>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row">
    <div  class="col-3">
      <h1>Recipes</h1>
    </div>
    <div class="col-3 mt-3">
      <%= form_with url: recipes_path, method: :get, local: true do |f| %>
        <%= f.text_field :search, :class => "search_field" %>
        <%= f.submit "Search", :class => "btn btn-outline-secondary" %>
      <% end %>
    </div>
    <div class="col-5 mt-3">
      <div class="row mb-2">
        <button type="button" class="btn btn-outline-secondary"><%= link_to "See Categories", categories_path %></button>
      </div>
      <div class="row mb-2">
        <button type="button" class="btn btn-outline-secondary"><%= link_to "Create Recipe", new_recipe_path %></button>
      </div>
      <div class="row mb-2">
        <button type="button" class="btn btn-outline-secondary"><%= link_to "Create Category", new_category_path %></button>
      </div>
    </div>
  </div>
  <div class="row mt-5">
     <%= link_to "Sort by new recipes", recipes_path(sort: "newest") %>
    <div class="col">
      <ul>
        <% @recipes.each do |recipe| %>
          <li>
            <% if @three_most_recent.include?(recipe) %>
              <p>
                <%= link_to recipe.title ,recipe_path(recipe) %> New!!!
              </p>
            <% else %>
              <p>
                <%= link_to recipe.title ,recipe_path(recipe) %>
              </p>
            <% end %>
          </li>
        <% end%>
      </ul>
      <% if @category %>
        <button type="button" class="btn btn-outline-secondary"><%= link_to "Back", recipes_path %></button>
      <% end%>
    </div>
    <% if @categories %>
      <div class="col">
        <h2>Search by categories</h2>
        <ul>
          <% @categories.each do |category| %>
            <li>
              <p>
                <%= link_to category.name, category_recipes_path(category) %>
              </p>
            </li>
          <% end%>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <h1>Create New Recipe</h1>
  <%= render "form" %>
  <div>
    <p><%= link_to 'Back', recipes_path %></p>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Recipe of <%= @recipe.title %></h1>
      <p><%= @recipe.description %></p>
      <% if @recipe.categories.any? %>
        <% @recipe.categories.each do |category| %>
          <span class="badge badge-success"><%= category.name %></span>
        <% end%>
      <% end %>
    </div>
    <div class="col mt-3">
      <button type="button" class="btn btn-outline-secondary"><%= link_to 'Edit this recipe', edit_recipe_path(@recipe) %></button>
      <button type="button" class="btn btn-outline-secondary"><%= link_to 'Delete this recipe', recipe_path(@recipe), method: :delete, data: { confirm: 'Are you sure?'} %></button>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <% if @recipe.ingredients.any? %>
        <div>
          <h4>Ingredients</h4>
        </div>
        <% @recipe.ingredients.each do |ingredient| %>
          <p><%= ingredient.name %> : <%= ingredient.qty %> <%= ingredient.uom %> <%= link_to "[Edit]",  edit_recipe_ingredient_path(@recipe, ingredient) %> <%= link_to "[Delete]",  recipe_ingredient_path(@recipe, ingredient), method: :delete, data: { confirm: 'Are you sure?'} %></p>
        <% end %>
        <span><button type="button" class="btn btn-outline-secondary"><%= link_to 'Add more Ingredients', new_recipe_ingredient_path(@recipe) %></button></span>
      <% else %>
        <div>
          <button type="button" class="btn btn-outline-secondary"><%= link_to 'Add Ingredients', new_recipe_ingredient_path(@recipe) %></button>
        </div>
      <% end%>
    </div>
    <div class="col">
      <% if @steps.any? %>
        <h4>Steps</h4>
        <% @steps.each do |step| %>
          <p><%= step.index%>: <%= step.description %><%= link_to "[Edit]", edit_recipe_step_path(@recipe, step) %><%= link_to "[Delete]", recipe_step_path(@recipe, step), method: :delete, data: {confirm: "Are you sure?"} %></p>
        <% end %>
        <span><button type="button" class="btn btn-outline-secondary"><%= link_to 'Add more Steps', new_recipe_step_path(@recipe) %></button></span>
      <% else %>
        <button type="button" class="btn btn-outline-secondary"><%= link_to 'Add more steps', new_recipe_step_path(@recipe) %></button>
      <% end %>
    </div>
  </div>
  <div class="mt-5 mb-5">
    <button type="button" class="btn btn-outline-secondary"><%= link_to 'Back', recipes_path %></button>
  </div>
</div>

app/views/steps/_form.html.erb
<%= form_with(model: @step, url: [@recipe, @step], local: true) do |f| %>
  <div class="field">
    <%= f.label :recipe_id %>
    <%= f.select :recipe_id, Recipe.order(:title).pluck(:title, :id) %>
  </div>

  <div class="field">
    <%= f.label :index %>
    <%= f.text_field :index %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h2>Edit this step</h2>

<%= render "form" %>

app/views/steps/new.html.erb
<h2>Add a new step</h2>

<%= render "form" %>